name: Build and Publish Ansible MCP Server image

on:
  push:
    paths:
      - 'ansible-mcp-server-docker/**'
      - '.github/workflows/ansible-mcp-server-publish.yaml'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-ansible-mcp-server:
    uses: spigell/my-shared-workflows/.github/workflows/docker-build-release.yaml@main
    secrets:
      gh-token: ${{ secrets.IMAGES_PUBLISH_TOKEN }}
    with:
      image-name: ansible-mcp-server
      context: ./ansible-mcp-server-docker
      version: 0.1.0
      build-args: |
        VSCODE_ANSIBLE_REF=main
