name: Build and Publish Universal Workbench

on:
  push:
    paths:
      - 'universal-workbench-docker/**'
      - '.github/workflows/universal-workbench-publish.yaml'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-universal-workbench:
    uses: spigell/my-shared-workflows/.github/workflows/docker-build-release.yaml@main
    secrets:
      gh-token: ${{ secrets.IMAGES_PUBLISH_TOKEN }}
    with:
      image-name: universal-workbench
      context: ./universal-workbench-docker
      version: '1.0.5'
      build-args: |
        UNIVERSAL_WORKBENCH_VERSION=1.0.5
        SPECIFY_VERSION=v0.0.90
      build-contexts: |
        shared=./shared

  trigger-downstreams:
    needs:
      - build-universal-workbench
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Universal Workbench Update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.IMAGES_PUBLISH_TOKEN }}
          event-type: universal-workbench-updated
          client-payload: '{"universal_tag":"${{ needs.build-universal-workbench.outputs.sha-tag }}"}'
