name: Build and Publish Universal Workbench

on:
  push:
    paths:
      - 'universal-workbench-docker/**'
      - '.github/workflows/universal-workbench-publish.yaml'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-universal-workbench:
    uses: spigell/my-shared-workflows/.github/workflows/docker-build-release.yaml@main
    secrets:
      gh-token: ${{ secrets.IMAGES_PUBLISH_TOKEN }}
    with:
      image-name: universal-workbench
      context: ./universal-workbench-docker
      version: '1.0.2'
      build-args: |
        UNIVERSAL_WORKBENCH_VERSION=1.0.2
      build-contexts: |
        shared=./shared

  update-manifest:
    needs:
      - build-universal-workbench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.IMAGES_PUBLISH_TOKEN }}
      - uses: ./.github/actions/update-workbench-manifest
        with:
          path: versions/universal-workbench.json
          tag: ${{ needs.build-universal-workbench.outputs.sha-tag }}
          commit-message: "chore(versions): update universal workbench tag to ${{ needs.build-universal-workbench.outputs.sha-tag }}"
